### ISSUE TITLE
Support for Live Reload during development

### ISSUE THREAD

**Issue by jmadson** [matt-rhys-jones/ionic-es2015#10]
Great job on the boilerplate! It would be ideal to have Live Reload support when running `ionic serve`, and to not require the `gulp build` prerequisite. I can look into this and submit a PR if I get something working.

**Comment by jmadson** [comment]
Closing issue, I see the gulp watch task is already working.

**Comment by matt-rhys-jones** [comment]
Hey, thanks for getting in touch. I'm sure there's a few things I've missed in general so issues/PRs are more than welcome. :)
